name: bobble_shooter
description: A simple bubble shooter game in Flutter
publish_to: "none" # is project ko pub.dev pe publish nahi karna

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # yahan tum apni game ke dependencies add kar sakte ho

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
